baseURL = "https://nthu-artscenter.github.io/"
title = "NTHU ArtsCenter"

defaultContentLanguage = "zh-tw"
defaultContentLanguageInSubdir = false

[outputs]
  section = ["HTML", "JSON"]
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
category = "categories"
tag = "tags"

