[[main]]
identifier = "about"
name = "About"
url = "/en/about/"
weight = 10

[[main]]
identifier = "history"
name = "History"
url = "/en/about/history/"
parent = "about"
weight = 20

[[main]]
identifier = "art_museum"
name = "Art Museum"
url = "https://cac.site.nthu.edu.tw/p/406-1549-221047,r11.php"
parent = "about"
weight = 25

[[main]]
identifier = "concert_hall"
name = "Concert Hall"
url = "https://flutistlin.wixsite.com/my-site-1"
parent = "about"
weight = 30

[[main]]
identifier = "museum"
name = "Museum"
url = "https://museum.site.nthu.edu.tw/"
parent = "about"
weight = 40

[[main]]
identifier = "activity"
name = "Activity"
url = "/en/about/activity/"
parent = "about"
weight = 50

[[main]]
identifier = "faculty"
name = "Faculty"
url = "/en/about/faculty/"
parent = "about"
weight = 60

[[main]]
identifier = "place"
name = "Exhibition Venue"
url = "/en/about/place"
parent = "about"
weight = 70

[[main]]
identifier = "collect_music"
name = "NTHU Chamber Ensemble"
url = "/en/collect/music/"
parent = "about"
weight = 80

[[main]]
identifier = "collect_art"
name = "NTHU Art Salon"
url = "/en/collect/art/"
parent = "about"
weight = 90




[[main]]
identifier = "programs"
name = "Programs"
url = "/en/exhibitions/"
weight = 100

[[main]]
identifier = "public_art"
name = "Public Art"
url = "/en/exhibitions/"
weight = 110
parent = "programs"

[[main]]
identifier = "visual_art"
name = "Visual Art"
url = "/en/exhibitions/"
weight = 120
parent = "programs"

[[main]]
identifier = "performing_art"
name = "Performing Art"
url = "/en/exhibitions/"
weight = 130
parent = "programs"

[[main]]
identifier = "film_art"
name = "Film Art"
url = "/en/exhibitions/"
weight = 140
parent = "programs"

[[main]]
identifier = "publication"
name = "Publications"
url = "/en/publications/"
weight = 200

[[main]]
identifier = "friends"
name = "Friends"
url = "/en/friends/"
weight = 210

[[main]]
identifier = "memory"
name = "Memory"
url = "/en/memory/"
weight = 190


[[main]]
identifier = "calendar"
name = "Calendar"
url = "/en/calendar/"
weight = 220
