backend:
  name: git-gateway
  #name: github
  #repo: arts-nthu/website
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - label: "資料"
    name: "data"
    files:
      - label: "輪播"
        name: "carousel"
        file: "data/carousel.toml"
        fields:
          - label: "首頁輪播"
            name: home
            widget: list
            fields:
              - { label: "標題", name: title, widget: string}
              - { label: "副標題", name: subtitle, widget: string}
              - { label: "圖片", name: image, widget: string}

      - label: "成員介紹"
        name: "faculty"
        file: "data/faculty.toml"
        fields:
          - label: "成員"
            name: curator
            widget: list
            fields:
              - {label: "姓名", name: name, widget: string}
              - {label: "英文姓名", name: en_name, widget: string}
              - {label: "職稱", name: title, widget: string}
              - {label: "英文職稱", name: en_title, widget: string}
              - {label: "學歷", name: education, widget: string}
              - {label: "英文學歷", name: en_education, widget: string}
  - name: "news"
    label: "消息"
    folder: "content/zh-tw/news"
    create: true
    summary: "{{start_date}}-{{slug}}"
    sortableFields: ['start_date', 'title']
    slug: "{{date}}-{{slug}}"
    fields:
      - { label: "標題", name: title, widget: string}
      - { label: "發佈日期", name: "date", widget: "datetime" }
      - { label: "草稿", name: "draft", widget: "boolean", default: false }
      - label: "開始日期"
        name: "start_date"
        widget: "datetime"
        format: "'YYYY-MM-DD'"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: "類型"
        name: "categories"
        widget: "select"
        multiple: true
        options: ["news"]
  - name: "post"
    label: "專欄"
    folder: "content/zh-tw/posts"
    create: true
    summary: "{{start_date}}-{{slug}}"
    sortableFields: ['start_date', 'title']
    view_filters:
      - label: 'Posts published in 2020'
        field: date
        pattern: '2020'
    slug: "{{start_date}}-{{slug}}"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "封面圖片", name: "cover", widget: "string" }
      - { label: "發佈日期", name: "date", widget: "datetime" }
      - label: "標籤"
        name: "tags"
        widget: "select"
        multiple: true
        options: []
      - { label: "草稿", name: "draft", widget: "boolean", default: false }
      - { label: "內容", name: "body", widget: "markdown" }
  - name: "exhibition" # Used in routes, e.g., /admin/collections/blog
    label: "展覽" # Used in the UI
    folder: "content/zh-tw/exhibitions" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    summary: "{{start_date}}-{{slug}}"
    sortableFields: ['start_date', 'title']
    slug: "{{start_date}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "標題", name: "title", widget: "string" }
      - { label: "封面圖片", name: "cover", widget: "string" }
      - { label: "發佈日期", name: "date", widget: "datetime" }
      - label: "類型"
        name: "categories"
        widget: "select"
        multiple: true
        options: ["visual_art", "public_art", "performing_art", "film_art", "ai_music"]
      - label: "主辦單位"
        name: "host"
        widget: "string"
        default: "清華大學藝術中心"
        required: false 
      - label: "表演者"
        name: "performer"
        widget: "string"
        required: false
      - label: "地點"
        name: "location"
        widget: "string"
        required: false
      - label: "開始日期"
        name: "start_date"
        widget: "datetime"
        format: "'YYYY-MM-DD'"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: "結束日期"
        name: "end_date"
        widget: "datetime"
        format: "'YYYY-MM-DD'"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: "開始時間"
        name: "daily_start_time"
        widget: "datetime"
        format: "'HH:mm'"
        dateFormat: "HH:mm"
        required: false
      - label: "結束時間"
        name: "daily_end_time"
        widget: "datetime"
        format: "'HH:mm'"
        dateFormat: "HH:mm"
        required: false
      - label: "票務資訊"
        name: "ticket_info"
        widget: "string"
        required: false
        default: ''
      - label: "註冊連結"
        name: "registration_link"
        required: false
        default: ''

      - { label: "內容", name: "body", widget: "markdown" }
